@echo off
setlocal enableDelayedExpansion enableextensions

REM DEFINE DELIMETER FOR WINDOWS IF SOMEONE WANTS TO TRANSCODE TO BASH.
SET DIRDELIMITER=\

REM CURRENT DIR
for /f %%i in ("%0") do set DIR=%%~dpi

REM TEMPLATE DIR
SET TMLP=%DIR%%DELIMETER%tmlp

REM TEMP DIR
REM SET TMP=C:\Windows\Temp
REM echo %1
SET TABLE=%1
SET FILTER=%2
SET TIPELDR=%3

SET ALIAS= AS FIELD
SET FILTER=!FILTER:"=! REM "
SET SQLSOURCEUSERPASS=userA/passA@source
SET SQLDESTUSERPASS=userB/passB@dest

SET TABLEDESC=%TMP%%DIRDELIMITER%GETFIELDS.TXT
SET TABLEGETDESC=%TMP%%DIRDELIMITER%GETFIELDS.SQL
SET FIELDS=%TMP%%DIRDELIMITER%FIELDS.TXT
SET SQLFIELDS=
SET CONTROL=%TMP%%DIRDELIMITER%CONTROL.TXT

SET LOADER_TMPL=%TMLP%%DIRDELIMITER%CONTROL_TMPL.TXT
SET SQL_TMPL=%TMLP%%DIRDELIMITER%SQL_TMPL.TXT

SET EXT_SQL=%TMP%%DIRDELIMITER%EXT_SQL.TXT

SET SQLFILE=%TMP%%DIRDELIMITER%FILE.SQL

ECHO "%TABLE%'S FIELDS" 

ECHO SPOOL %TABLEDESC% > %TABLEGETDESC%
ECHO SET TERMOUT off >> %TABLEGETDESC%
ECHO DESC %TABLE% >> %TABLEGETDESC%
ECHO QUIT >> %TABLEGETDESC%

ECHO "EXECUTE SCRIPT %TABLEGETDESC%"

sqlplus %SQLDESTUSERPASS% @%TABLEGETDESC%

ECHO "HANDLEING FIELDS TO SQL AND LOADER FILES"

FOR /F %%A IN (%TABLADESC%) DO (
	REM
	REM COUNTING LINE TO SKIP FIRST 2 LINES
	REM
	SET /A CONT+=1
	IF !CONT! GTR 2 (
		IF !CONT! GTR 3 (
			ECHO ,%%A >> %CAMPOS%
			SET SQLCAMPOS=!SQLCAMPOS!^|^|^'^|^|^'^|^|%%A
		) ELSE (
			ECHO %%A > %CAMPOS%
			SET SQLCAMPOS=%%A
		)
	)
)
REM LAST DELIMITE OF FIELD TO SQL 
SET SQLFIELDS=!SQLFIELDS!^|^|^'^|^|^'^%ALIAS%

ECHO. > %CONTROL%
FOR /F "tokens=*" %%A IN (%LOADER_TMPL%) DO (
  ECHO %%A >> %CONTROL%
)

TYPE %FIELDS% >> %CONTROL%
ECHO ) >> %CONTROL%
ECHO BEGINDATA >> %CONTROL%

ECHO. > %SQLFILE%

FOR /F "tokens=* eol=" %%B IN (%SQL_TMPL%) DO (
  ECHO %%B >> %SQLFILE%
)

ECHO "EXECUTE SQL SCRIPT %SQLFILE%"
sqlplus %SQLSOURCEUSERPASS% @%SQLFILE%

TYPE %EXT_SQL% >> %CONTROL%

ECHO "EXECUTE SQL LOADER"
sqlldr %SQLDESTUSERPASS% control=%CONTROL% rows=10000 direct=true
